apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnd
  namespace: svc
  labels:
    app: rnd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rnd
  template:
    metadata:
      labels:
        app: rnd
    spec:
      {{- if eq .Values.env "prod" }}
      nodeSelector:
        role: {{ .Values.services.nodeSelector }}
      {{- end }}
      containers:
      - name: rnd
        image: bahamagames/rnd:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: '10m'
            memory: '30Mi'
          limits:
            cpu: '50m'
            memory: '50Mi'
        env:
          - name: REDIS_LOCAL_HOST
            value: redis.default.svc.cluster.local
          - name: REDIS_LOCAL_PORT
            value: '6379'
          - name: REDIS_REMOTE_USER_NAME
            valueFrom:
              configMapKeyRef:
                name: svc
                key:  REDIS_REMOTE_USER_NAME
                optional: true
          - name: REDIS_REMOTE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: svc
                key:  REDIS_REMOTE_PASSWORD
                optional: true
          - name: REDIS_REMOTE_HOST
            valueFrom:
              configMapKeyRef:
                name: svc
                key:  REDIS_REMOTE_HOST
                optional: true
          - name: REDIS_REMOTE_PORT
            valueFrom:
              configMapKeyRef:
                name: svc
                key:  REDIS_REMOTE_PORT
                optional: true