apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.remoteEntryPoint.namespace}}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name:                                   {{.Values.remoteEntryPoint.namespace}}
  namespace:                              {{.Values.remoteEntryPoint.namespace}}
data:             
  REDIS_LOCAL_HOST:                       {{.Values.configMap.data.REDIS_LOCAL_HOST}}
  REDIS_LOCAL_PORT:                       '{{.Values.configMap.data.REDIS_LOCAL_PORT}}'
  REDIS_REMOTE_USER_NAME:                 {{.Values.configMap.data.REDIS_REMOTE_USER_NAME}}
  REDIS_REMOTE_HOST:                      {{.Values.configMap.data.REDIS_REMOTE_HOST}}
  REDIS_REMOTE_PORT:                      '{{.Values.configMap.data.REDIS_REMOTE_PORT}}'
---

apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.remoteEntryPoint.namespace}}
  namespace: {{.Values.remoteEntryPoint.namespace}}
data:
  ACCESS_SECRET: {{.Values.secret.data.ACCESS_SECRET}}
  REDIS_REMOTE_PASSWORD: {{.Values.secret.data.REDIS_REMOTE_PASSWORD}}
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: {{ .Values.remoteEntryPoint.namespace }}
 namespace: {{ .Values.remoteEntryPoint.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.remoteEntryPoint.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.remoteEntryPoint.namespace }}
                port:
                  number: {{ .Values.remoteEntryPoint.ingress.port }}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.remoteEntryPoint.name }}
  name: {{ .Values.remoteEntryPoint.namespace }}
  namespace: {{ .Values.remoteEntryPoint.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.remoteEntryPoint.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.remoteEntryPoint.ingress.port }}
      targetPort: {{ .Values.remoteEntryPoint.ports.tcp }}