apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.services.namespace}}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name:                                   {{.Values.services.namespace}}
  namespace:                              {{.Values.services.namespace}}
data:             
  REDIS_LOCAL_HOST:                       {{.Values.configMap.data.REDIS_LOCAL_HOST}}
  REDIS_LOCAL_PORT:                       '{{.Values.configMap.data.REDIS_LOCAL_PORT}}'
  REDIS_REMOTE_USER_NAME:                 {{.Values.configMap.data.REDIS_REMOTE_USER_NAME}}
  REDIS_REMOTE_HOST:                      {{.Values.configMap.data.REDIS_REMOTE_HOST}}
  REDIS_REMOTE_PORT:                      '{{.Values.configMap.data.REDIS_REMOTE_PORT}}'
  
  DGSM_TICK_RATE:                         '{{.Values.configMap.data.DGSM_TICK_RATE}}'
  DGSM_IDLE_POOL_SIZE:                    '{{.Values.configMap.data.DGSM_IDLE_POOL_SIZE}}'
  DGS_POD_FPS:                            '{{.Values.configMap.data.DGS_POD_FPS}}'
  DGS_POD_NAME:                           {{.Values.configMap.data.DGS_POD_NAME}}
  DGS_POD_IMAGE:                          {{.Values.configMap.data.DGS_POD_IMAGE}}
  DGS_POD_VERSION:                        {{.Values.configMap.data.DGS_POD_VERSION}}
  DGS_POD_TICKRATE:                       '{{.Values.configMap.data.DGS_POD_TICKRATE}}'
  DGS_POD_NAMESPACE:                      {{.Values.configMap.data.DGS_POD_NAMESPACE}}
  DGS_POD_RESOURCES_REQUEST_CPU:          '{{.Values.configMap.data.DGS_POD_RESOURCES_REQUEST_CPU}}'
  DGS_POD_RESOURCES_REQUEST_MEM:          '{{.Values.configMap.data.DGS_POD_RESOURCES_REQUEST_MEM}}'
  DGS_POD_RESOURCES_LIMITS_CPU:           '{{.Values.configMap.data.DGS_POD_RESOURCES_LIMITS_CPU}}'
  DGS_POD_RESOURCES_LIMITS_MEM:           '{{.Values.configMap.data.DGS_POD_RESOURCES_LIMITS_MEM}}'
  DGS_POD_SIDECAR_NAME:                   {{.Values.configMap.data.DGS_POD_SIDECAR_NAME}}
  DGS_POD_SIDECAR_VERSION:                {{.Values.configMap.data.DGS_POD_SIDECAR_VERSION}}
  DGS_POD_SIDECAR_RESOURCES_REQUEST_CPU:  '{{.Values.configMap.data.DGS_POD_SIDECAR_RESOURCES_REQUEST_CPU}}'
  DGS_POD_SIDECAR_RESOURCES_REQUEST_MEM:  '{{.Values.configMap.data.DGS_POD_SIDECAR_RESOURCES_REQUEST_MEM}}'
  DGS_POD_SIDECAR_RESOURCES_LIMITS_CPU:   '{{.Values.configMap.data.DGS_POD_SIDECAR_RESOURCES_LIMITS_CPU}}'
  DGS_POD_SIDECAR_RESOURCES_LIMITS_MEM:   '{{.Values.configMap.data.DGS_POD_SIDECAR_RESOURCES_LIMITS_MEM}}'
---

apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.services.namespace}}
  namespace: {{.Values.services.namespace}}
data:
  ACCESS_SECRET: {{.Values.secret.data.ACCESS_SECRET}}
  REDIS_REMOTE_PASSWORD: {{.Values.secret.data.REDIS_REMOTE_PASSWORD}}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.redis.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}