apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis/redis-stack
      ports:
        - containerPort: 6379
          name: redis